// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet/services.proto

package wallet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TxSrvc service

type TxSrvcClient interface {
	// ProcessTx handles the UTXO transaction request, TxIN -> TxOUT
	ProcessTx(ctx context.Context, in *TXs, opts ...grpc.CallOption) (*ProcessTxResponse, error)
	QueryTx(ctx context.Context, in *QueryTxRequest, opts ...grpc.CallOption) (*TX, error)
	QueryUTXO(ctx context.Context, in *QueryUTXORequest, opts ...grpc.CallOption) (*QueryUTXOResponse, error)
}

type txSrvcClient struct {
	cc *grpc.ClientConn
}

func NewTxSrvcClient(cc *grpc.ClientConn) TxSrvcClient {
	return &txSrvcClient{cc}
}

func (c *txSrvcClient) ProcessTx(ctx context.Context, in *TXs, opts ...grpc.CallOption) (*ProcessTxResponse, error) {
	out := new(ProcessTxResponse)
	err := grpc.Invoke(ctx, "/wallet.TxSrvc/ProcessTx", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txSrvcClient) QueryTx(ctx context.Context, in *QueryTxRequest, opts ...grpc.CallOption) (*TX, error) {
	out := new(TX)
	err := grpc.Invoke(ctx, "/wallet.TxSrvc/QueryTx", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *txSrvcClient) QueryUTXO(ctx context.Context, in *QueryUTXORequest, opts ...grpc.CallOption) (*QueryUTXOResponse, error) {
	out := new(QueryUTXOResponse)
	err := grpc.Invoke(ctx, "/wallet.TxSrvc/QueryUTXO", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TxSrvc service

type TxSrvcServer interface {
	// ProcessTx handles the UTXO transaction request, TxIN -> TxOUT
	ProcessTx(context.Context, *TXs) (*ProcessTxResponse, error)
	QueryTx(context.Context, *QueryTxRequest) (*TX, error)
	QueryUTXO(context.Context, *QueryUTXORequest) (*QueryUTXOResponse, error)
}

func RegisterTxSrvcServer(s *grpc.Server, srv TxSrvcServer) {
	s.RegisterService(&_TxSrvc_serviceDesc, srv)
}

func _TxSrvc_ProcessTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TXs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxSrvcServer).ProcessTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.TxSrvc/ProcessTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxSrvcServer).ProcessTx(ctx, req.(*TXs))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxSrvc_QueryTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxSrvcServer).QueryTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.TxSrvc/QueryTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxSrvcServer).QueryTx(ctx, req.(*QueryTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TxSrvc_QueryUTXO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUTXORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxSrvcServer).QueryUTXO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.TxSrvc/QueryUTXO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxSrvcServer).QueryUTXO(ctx, req.(*QueryUTXORequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TxSrvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.TxSrvc",
	HandlerType: (*TxSrvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessTx",
			Handler:    _TxSrvc_ProcessTx_Handler,
		},
		{
			MethodName: "QueryTx",
			Handler:    _TxSrvc_QueryTx_Handler,
		},
		{
			MethodName: "QueryUTXO",
			Handler:    _TxSrvc_QueryUTXO_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet/services.proto",
}

func init() { proto.RegisterFile("wallet/services.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xd7, 0x4b, 0x65, 0xe3, 0x41, 0x08, 0x28, 0x6e, 0x8f, 0x7b, 0xdf, 0x04, 0x5d, 0xfc,
	0x03, 0xfd, 0x03, 0x6a, 0x8d, 0x50, 0xbc, 0xa5, 0x71, 0x68, 0x8b, 0x6d, 0xa6, 0x66, 0xd2, 0x1a,
	0xff, 0x97, 0x3f, 0x50, 0x6c, 0x1a, 0x45, 0xf0, 0xf8, 0xde, 0xf7, 0xde, 0x1b, 0x86, 0x5d, 0xbc,
	0xeb, 0xbe, 0x07, 0x2f, 0x09, 0xdc, 0xdc, 0x19, 0x20, 0x31, 0x3a, 0xf4, 0xc8, 0xb3, 0x68, 0xe7,
	0xe7, 0x2b, 0xf6, 0x21, 0x82, 0x9b, 0xcf, 0x13, 0x96, 0xa9, 0xf0, 0xe8, 0x66, 0xc3, 0x6f, 0xd9,
	0xf6, 0xde, 0xa1, 0x01, 0x22, 0x15, 0xf8, 0x99, 0x88, 0x49, 0xa1, 0x2a, 0xca, 0x77, 0x49, 0xfc,
	0xf0, 0x12, 0x68, 0x44, 0x4b, 0xb0, 0xdf, 0x70, 0xc9, 0x4e, 0x1f, 0x26, 0x70, 0x1f, 0x2a, 0xf0,
	0xcb, 0x94, 0x5b, 0x8d, 0x12, 0xde, 0x26, 0x20, 0x9f, 0xb3, 0xdf, 0xb1, 0xfd, 0x86, 0x17, 0x6c,
	0xbb, 0xf0, 0x27, 0x55, 0xdd, 0xf1, 0xab, 0x3f, 0x95, 0x6f, 0x2b, 0x95, 0x76, 0xff, 0x90, 0x74,
	0xb4, 0x38, 0x3e, 0x5f, 0x37, 0x9d, 0x6f, 0xa7, 0x5a, 0x18, 0x1c, 0xa4, 0x76, 0x41, 0x5b, 0xd3,
	0xea, 0xce, 0x4a, 0x7a, 0x79, 0x3d, 0x34, 0x78, 0x30, 0x38, 0x0c, 0x68, 0xe5, 0xf2, 0x23, 0xc9,
	0x38, 0x54, 0x67, 0x8b, 0x3c, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xcb, 0xa9, 0x5a, 0x24,
	0x01, 0x00, 0x00,
}
